### PR TITLE
Fix #7 & #8

### LINKED ISSUE #7: Allow change of default dashboard
Add capability to change default dashboard i.e. "pin" the dashboard

### PR DESCRIPTION
**Pull request by rajyraman**
Can choose default dashboard and format.

### CODE REVIEW

**Comment by MscrmTools** [comment]
Thank you for the PR but I guess there is two "issues":
1/ You are using Early Bound Entities, which might lead to a conflict if other plugins use Early Bound Entities too. The (very) best practice for XrmToolBox is to use Late Bound Entities
2/ You added  a new nuget package but I don't see any ILMerge command to embed this package, unless it just adds some class

**Comment by rajyraman** [comment]
Reg 1: There are too many attributes and the possibility of messing up the type or name is quite high. Is there a way around this?

Reg 2: This is a .net Framework dll https://www.nuget.org/packages/System.ValueTuple/

**Comment by MscrmTools** [comment]
1/ No work around here since this is a problem with the way OrganizationServiceProxy is created. If it finds multiple definition of the same entity across plugins, it fails to connect.
2/ OK

I will merge your PR and replace EarlyBound with LateBound entities

**Comment by rajyraman** [comment]
Done.

**Comment by rajyraman** [comment]
Any timeline on when this will be merged?

**Comment by MscrmTools** [comment]
Yes, I'll do that today

**Comment by rajyraman** [comment]
Thank you Tanguy 😄

**Pull request merged**
