### PR TITLE
Handle 'Disabled User' and 'No Security Roles' errors

### PR DESCRIPTION
**Pull request by bwmodular**
If the user whose settings are being updated have no security roles or are disabled, you will no see a dialogue box like this:
image

I did try adding a logging pane, but couldn't get it working, so thought it was more important to just fix the error. Logging can come later if need be.

This is a fix for issue #17

### CODE REVIEW

**Comment by MscrmTools** [comment]
Not a fan of creating a full form by code but I accept the PR :)

**Comment by bwmodular** [comment]
:-)
Yes, I don't like the clunkiness of the solution but default MessageBox buttons would have been too confusing I think.

**Comment by MscrmTools** [comment]
I meant you could have created a new form (by design) instead of creating it through code only

**Comment by bwmodular** [comment]
Good point - I blame Mr Google for that (and the fact that I've never worked with Windows Forms before)!! 
;-)

**Pull request merged**
